sudo: required
os: linux
language: minimal
addons:
  apt:
    packages:
    - docker-ce
git:
  depth: 4
services:
  - docker

script:
  - docker version
  - docker build --no-cache --tag lltest/gamesvr-hldms-freeplay --tag lacledeslan/gamesvr-hldms-freeplay --build-arg BUILDNODE=TravisCI -f Dockerfile.linux .
  - docker run -it --rm lltest/gamesvr-hldms-freeplay ./ll-tests/gamesvr-hldms-freeplay.sh

notifications:
  slack:
    secure: KO9HN7W12dM1ltoeXRq9+8/wpB4qSEILdGz/D9YvaPL9sZIzolwTcNTh8AY7B0hNHolxO3PtWO8QYGnuwWYHM/bhvGyScHRLh2DKX6vAx2Jc0DFkdM99vZM1GvH262r3+jEPCfrUwydkXhkDAt0s5trH8on1pjmfFs8R/Jvwcgeu4n78twCApYhLy3zNj0bBtwj3UbLELkl92aU9yKe0UlzCUtp8Vh8gEvAhbOFI3osJmFWUfb/D6Q6uFLDWvUgPS/QbzdrawNJqsFgNQqFp/SHDJUV3WkaKkIPCPwkqNLn6wzfCxRX3XNip+fDkUcq26/n0mkuD+PNxqfJsWXe9Zr1MW7+Uu2t8Bjph/QPq1pdlyIYuWKNyHLcRtHl+ax7x7lAkAeoFNkqNKXScRBX0zZw74i8Bm1VIVsGE4u5K7dmCHz9vq8ECdWXqfzcNHOZAQunR4Aw7GI0kbTPrLPgnjxbYkkqT1eJKhls8mFYiJhai7/u7OTocJxSgU7VCff1qsobmqtqWwy7Dnhjy2zuWCn2Xrvx2AWb1Zxh/VvMXLaMlu412PC1Oe16j7M4v+dh1dPk+XeB5kCYRZo2rGafpitHI9okmHLAVvtDHTHhb3q0iLi/FSeSNCBpxvEUp8AZOr5oxUHc+mnxQhKwQMdwFXAWWtp329bZzminS3rBEy2Y=

before_deploy:
  - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASS";
deploy:
  provider: script
  script: docker push lacledeslan/gamesvr-hldms-freeplay
  on:
    branch: master
